### ISSUE TITLE
Valid input for 031$p

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#993] opened 2020-09-30 09:40 UTC
It would be useful for the 031$p to only accept certain characters. See https://github.com/rism-international/tasks/issues/781 for a start (which was based on the BnF import).

**Comment by xhero** [comment] 2021-11-25 07:40
Duplicate of #901, this is going to be fixed with the new Verovio error display

**Closed by xhero** 2021-11-25 07:40 UTC
