### ISSUE TITLE
Users cannot change password

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#515] opened 2017-09-06 08:17 UTC
It is enabled only for admins - in AA this is possible, it was probably lost in the transition to the RISM sidebar.

**Comment by HirschSt** [comment] 2017-09-14 11:44
This is a feature, not a bug :-) to prevent that users can take highly unsecure passwords.

**Comment by lpugin** [comment] 2017-09-14 11:53
This makes sense. @cgueggi can we close it?

**Comment by cgueggi** [comment] 2017-09-14 12:03
Hmm, I'm not sure if it is really practicable and I don't see much sense in it. In my opinion a hint to use high secure passwords should be enough.

**Comment by cgueggi** [comment] 2017-09-14 12:07
By the way: my current pw (I recieved from you) doesn't seem to be really high secure...

**Comment by HirschSt** [comment] 2017-09-14 12:11
Really high secure would be a password of 24 characters length, so we made a compromise between security and usability. Nevertheless, providing the password was never an issue in the last year, because it is in the workflow of creating new users.

**Comment by xhero** [comment] 2017-09-14 12:12
I think too complex password was the complaint ;)

**Comment by lpugin** [comment] 2017-09-14 12:17
We need to think about it because if we make it changeable we will indeed always end up with users choosing "1234" or "rism" ...

**Comment by cgueggi** [comment] 2017-09-14 12:25
OK, let's think and talk about it next week Laurent. As "editor" I would really estimate to create my own pw, seems logical to me (as it does for all of my Swiss colleagues).

**Comment by HirschSt** [comment] 2017-09-14 12:43
> choosing "1234" or "rism" ...

Hey, you've stolen my pw :-)

**Comment by xhero** [comment] 2017-09-14 12:57
We could also have a password validator that rejects too unsecure passwords (like 1234 etc)

**Comment by lpugin** [comment] 2017-09-14 13:14
Yes, but I think the main issue is that we modified ActiveAdmin for the menus to be always at the same place and to look the same everywhere, and as far as I remember this change caused some issues with passwords when they are left blank. If we leave it like and just make the password editable, this it will be problematic and users will complain that then cannot change their settings without giving the password again every time they save their user account (which would indeed be an usual interface behaviour). I will look on Monday what we can do but I know this is not straight-forward.

**Comment by xhero** [comment] 2017-09-25 11:53
What should we do with this? I can move it to 3.7

**Comment by lpugin** [comment] 2017-09-25 12:05
I am having a look

**Comment by lpugin** [comment] 2017-09-25 13:35
I pushed a change for editors (only) to be able to change their password. We need to discuss it.

**Comment by HirschSt** [comment] 2017-09-26 06:32
As I had said previously there was a decision by ZR that users should not be able to change their password, including editors. If there is a request to change this policy I can make a proposition here and we can look for further proceeding. It's not correct to change this without consulting us.

**Comment by lpugin** [comment] 2017-09-26 06:34
Yes, we indeed need to discuss it.

**Comment by xhero** [comment] 2017-09-26 08:14
I rolled back the code and moved to 3.7

**Comment by xhero** [comment] 2018-01-22 08:48
What is the status of this? I'm moving to wishlist

**Closed** 2021-05-31 12:15 UTC
Labels: ActiveAdmin (UI), Users
